<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE isys [
        <!ELEMENT isys (info|queries)*>
        <!ELEMENT info (title|version|requirement|directory|revision|release)*>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT version (#PCDATA)>
        <!ELEMENT requirement (revision|version)*>
        <!ELEMENT revision (#PCDATA)>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT release (#PCDATA)>
        <!ELEMENT queries (query)*>
        <!ELEMENT query (id|title|check|errmsg|sql)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT check (#PCDATA)>
        <!ATTLIST check ident CDATA #REQUIRED>
        <!ELEMENT errmsg (#PCDATA)>
        <!ELEMENT sql (exec)*>
        <!ELEMENT exec (#PCDATA)>
        <!ATTLIST exec ident CDATA #REQUIRED>
        ]>
<isys>
    <info>
        <title>i-doit v1.12</title>
        <version>1.12</version>
        <requirement>
            <revision>201811100</revision>
            <version>1.11</version>
        </requirement>
        <directory>v1.12</directory>
        <!--
        LF: Changed this to: <year>1<major><minor> with major and minor beeing a two digit number:
        201711000 => 2017 1.10.00
        201811221 => 2018 1.12.21
        ...
        -->
        <revision>201811200</revision>
        <release>2018-12-17</release>
    </info>
    <queries>

        <query>
            <id>1</id>
            <title>Adding field: isys_report__multivalue_grouping</title>
            <check ident="C_ADD_FIELD">isys_report, isys_report__compressed_multivalue_results</check>
            <errmsg></errmsg>
            <sql>
                <exec ident="true">
                    ALTER TABLE `isys_report` CHANGE isys_report__compressed_multivalue_results isys_report__compressed_multivalue_results TINYINT(1) UNSIGNED DEFAULT 0;
                </exec>
            </sql>
        </query>

        <query>
            <id>2</id>
            <title>Replace _dns_domain with _search_domain</title>
            <check ident="C_VALUE_EXISTS">SELECT * FROM isys_report WHERE isys_report__querybuilder_data LIKE '%_dns_domain%';</check>
            <errmsg></errmsg>
            <sql>
                <exec ident="false">
                    UPDATE isys_report SET isys_report__querybuilder_data = REPLACE(isys_report__querybuilder_data, '_dns_domain', '_search_domain')
                    WHERE isys_report__querybuilder_data LIKE '%_dns_domain%';
                </exec>
            </sql>
        </query>

        <query>
            <id>3</id>
            <title>Adding field: isys_report__show_html</title>
            <check ident="C_ADD_FIELD">isys_report, isys_report__show_html</check>
            <errmsg></errmsg>
            <sql>
                <exec ident="false">
                    ALTER TABLE `isys_report` ADD COLUMN `isys_report__show_html` TINYINT(1) UNSIGNED DEFAULT 0;
                </exec>
            </sql>
        </query>
        <query>
            <id>4</id>
            <title>Set default tenant setting cmdb.renew-properties to 0 to renew categories info</title>
            <check ident="C_VALUE_EXISTS">
                SELECT isys_settings__key FROM `isys_settings` WHERE isys_settings__key = 'cmdb.renew-properties' AND isys_settings__isys_mandator__id = 0;
            </check>
            <sql>
                <exec ident="false">
                    INSERT INTO `isys_settings` VALUES ('cmdb.renew-properties','1',0);
                </exec>
            </sql>
        </query>
    </queries>
</isys>
